name: list-files linux CI

#on: [push]
# TODO: code is being rewritten. Re-enable when ready
on: [pull_request]


jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make [default]
      run: make
    - name: make test [default]
      run: make test
    - name: make clean && make [without-ouner-group-names]
      run: make cleanall && make WITHOUT_ID=true
    - name: make test [without-ouner-group-names]
      run: make test
    # TODO: not creating binary package, only want to do this for a release
    #- name: creating package [Linux]
    #  run: ./package.sh 1
    #- name: uploading package binary
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: linux_binary
    #    path: ./pkg/lf-v*
