name: list-files macos CI

# TODO: only run on pull request, otherwise it runs too often
on: [pull_request]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make [default]
      run: make
    - name: make test [default]
      run: make test
    - name: make clean && make [without-ouner-group-names]
      run: make cleanall && make WITHOUT_ID=true
    - name: make test [without-ouner-group-names]
      run: make test
    # TODO: not creating binary right now, since it is not codesigned and whatnot
    # need to build for macOS local
    #- name: creating package [macOS]
    #  run: ./package.sh 2
    #- name: uploading package binary
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: macos_binary
    #    path: ./pkg/lf-v*

