name: list-files CI

on: [push]

jobs:
  testUbuntuLatest:
    name: test
    runs-on: ubuntu-latest
       steps:
        - uses: actions/checkout@v1
        - name: make [default]
          run: make
        - name: make test [default]
          run: make test
        - name: make clean && make [without-ouner-group-names]
          run: make cleanall && make WITHOUT_ID=true
        - name: make test [without-ouner-group-names]
          run: make test
 testMacOSLatest:
    runs-on: macos-latest
    needs: testUbuntuLatest
    name: test
      steps:
        - uses: actions/checkout@v1
        - name: make [default]
          run: make
        - name: make test [default]
          run: make test
        - name: make clean && make [without-ouner-group-names]
          run: make cleanall && make WITHOUT_ID=true
        - name: make test [without-ouner-group-names]
          run: make test
